/* eslint-disable */

module.exports = {
  'GET /ys/scUserInfo/currentUser': {
    "resultMsg": "获取用户成功test",
    "resultCode": 0,
    "data": {
      "userId": 10,
      "baseAccount": "admin",
      "basePassword": "3783dce43d83b8bcca239f972404d1b5",
      "scPointInfoDtoList": [
        {
          "id": 72,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010001",
          "pointName": "南昌北公安检查站",
          "pointAddress": "南昌北收费站（S49西一环南向）",
          "jd": "115.70588235294117",
          "wd": "28.705882352941178",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "黄sir",
          "directorPhone": "13800138000",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "02",
          "gajczDwjc": "cwq",
          "gajczZz": "黄sir",
          "gajczZbdh": "1380018000",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "1",
            "desc": "红色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "",
          "crossingIndexCode": ""
        },
        {
          "id": 75,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010003",
          "pointName": "昌西南公安检查站",
          "pointAddress": "江西省沪昆高速公路昌西南收费站",
          "jd": "115.84602355957031",
          "wd": "28.796626586914062",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "11",
          "directorPhone": "13800138000",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "01",
          "gajczDwjc": null,
          "gajczZz": "11",
          "gajczZbdh": "11",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "4",
            "desc": "蓝色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "",
          "crossingIndexCode": ""
        },
        {
          "id": 76,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010004",
          "pointName": "西山公安检查站",
          "pointAddress": "江西省320国道新建区草山村附近",
          "jd": "116.06025695800781",
          "wd": "28.688735961914062",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "蒲sir",
          "directorPhone": "13800138000",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "01",
          "gajczDwjc": null,
          "gajczZz": "13800138000",
          "gajczZbdh": "13800138000",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "4",
            "desc": "蓝色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "",
          "crossingIndexCode": ""
        },
        {
          "id": 77,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010005",
          "pointName": "金桥公安检查站",
          "pointAddress": "江西省昌九大道与新祺周大道交界",
          "jd": "116.04377746582031",
          "wd": "28.776626586914062",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "张sir",
          "directorPhone": "13800138000",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "01",
          "gajczDwjc": null,
          "gajczZz": "张sir",
          "gajczZbdh": "11",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "4",
            "desc": "蓝色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "",
          "crossingIndexCode": ""
        },
        {
          "id": 78,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010006",
          "pointName": "广福公安检查站",
          "pointAddress": "江西省105国道南昌县广福段 ",
          "jd": "116.14265441894531",
          "wd": "28.350906372070312",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "13800138000",
          "directorPhone": "13800138000",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "01",
          "gajczDwjc": null,
          "gajczZz": "13800138000",
          "gajczZbdh": "13800138000",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "4",
            "desc": "蓝色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "",
          "crossingIndexCode": ""
        },
        {
          "id": 79,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010007",
          "pointName": "衙前公安检查站",
          "pointAddress": "江西省320国道进贤县衙前段 (往抚州东乡方向出入口)",
          "jd": "116.07398986816406",
          "wd": "28.567886352539062",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "黄sir",
          "directorPhone": "13800138000",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "01",
          "gajczDwjc": "ss",
          "gajczZz": "ss",
          "gajczZbdh": "ss",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "4",
            "desc": "蓝色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "",
          "crossingIndexCode": ""
        },
        {
          "id": 80,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010008",
          "pointName": "三里公安检查站",
          "pointAddress": "江西省昌万公路进贤县三里段 (往上饶余干方向出入口)",
          "jd": "115.75813293457031",
          "wd": "28.479995727539066",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "周sir",
          "directorPhone": "13800138000",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "01",
          "gajczDwjc": "wa",
          "gajczZz": "周sir",
          "gajczZbdh": "13800138000",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "4",
            "desc": "蓝色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "",
          "crossingIndexCode": ""
        },
        {
          "id": 81,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010009",
          "pointName": "长山晏公安检查站",
          "pointAddress": "江西省316国道进贤县长山晏段 (往抚州临川方向出入口)",
          "jd": "116.07398986816406",
          "wd": "28.447036743164062",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "黄sir",
          "directorPhone": "13800138000",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "01",
          "gajczDwjc": "swa",
          "gajczZz": "黄sir",
          "gajczZbdh": "13800138000",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "4",
            "desc": "蓝色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "",
          "crossingIndexCode": ""
        },
        {
          "id": 82,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010010",
          "pointName": "东阳公安检查站",
          "pointAddress": "江西省105国道安义县东阳段 (往九江永修方向出入口)",
          "jd": "115.70320129394531",
          "wd": "28.606338500976562",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "黄sir",
          "directorPhone": "13800138000",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "01",
          "gajczDwjc": "10",
          "gajczZz": "黄sir",
          "gajczZbdh": "13800138000",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "4",
            "desc": "蓝色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "",
          "crossingIndexCode": ""
        },
        {
          "id": 83,
          "pointType": {
            "code": "0",
            "desc": "检查站"
          },
          "level": 4,
          "parentCode": "510106000001",
          "checkCode": "5101060000010011",
          "pointName": "温圳公安检查站",
          "pointAddress": "进贤县温圳镇316国道与320国道交叉口(交警大队温圳中队)",
          "jd": "116.1024",
          "wd": "28.3587",
          "provinceCode": "360000000000",
          "provinceName": "江西省",
          "cityCode": "360100000000",
          "cityName": "南昌市",
          "areaCode": "360102000000",
          "areaName": "东湖区",
          "directorName": "朱伏龙",
          "directorPhone": "15080102183",
          "baseTelephone": null,
          "upload": "0",
          "createDate": null,
          "updateDate": null,
          "gajczJgjbdm": null,
          "gajczGajczlbdm": "03",
          "gajczDwjc": null,
          "gajczZz": "朱伏龙",
          "gajczZbdh": "15080102183",
          "gajczDj": null,
          "parentName": "",
          "planLevel": {
            "code": "4",
            "desc": "蓝色预警"
          },
          "stateRunning": 0,
          "cameraIndexCode": "01577685566777018586,01577685764764018591,01577689895721018855",
          "crossingIndexCode": "f8ab189d405d48a3bc586e8a9bd4fbd9"
        }
      ],
      "baseName": "超管",
      "gender": {
        "name": "MAN",
        "desc": "男"
      },
      "policeType": {
        "name": "TRAFFIC_POLICE",
        "desc": "交警"
      },
      "scRoleDto": {
        "roleId": 9,
        "roleName": "admin",
        "roleDescribe": "超级管理员",
        "accountType": {
          "name": "ADMIN",
          "desc": "系统管理员"
        },
        "menuTreeLists": [
          {
            "menuId": 4,
            "menuName": "检查站管理",
            "menuType": "MENU",
            "menuSort": 4,
            "menuPath": "/erp/check",
            "menuIcon": "checkIcon",
            "menuPid": 0,
            "englishName": null,
            "open": false,
            "selected": false,
            "children": [
              {
                "menuId": 18,
                "menuName": "卡点管理",
                "menuType": "MENU",
                "menuSort": 1,
                "menuPath": "/erp/check/checkpoint/list",
                "menuIcon": "icon-kakou-kakou",
                "menuPid": 4,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 19,
                "menuName": "设备管理",
                "menuType": "MENU",
                "menuSort": 2,
                "menuPath": "/erp/check/equipment/list",
                "menuIcon": "iconshebeiguanli",
                "menuPid": 4,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 20,
                "menuName": "警备管理",
                "menuType": "MENU",
                "menuSort": 3,
                "menuPath": "/erp/check/guard/list",
                "menuIcon": "iconshebeiguanli",
                "menuPid": 4,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 21,
                "menuName": "公文预案管理",
                "menuType": "MENU",
                "menuSort": 4,
                "menuPath": "/erp/check/official/list",
                "menuIcon": "iconyuan",
                "menuPid": 4,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 22,
                "menuName": "勤务管理",
                "menuType": "MENU",
                "menuSort": 5,
                "menuPath": "/erp/check/dutyconfig/list",
                "menuIcon": "iconqinwu-copy",
                "menuPid": 4,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              }
            ]
          },
          {
            "menuId": 5,
            "menuName": "过检核查管理",
            "menuType": "MENU",
            "menuSort": 5,
            "menuPath": "/erp/inspect",
            "menuIcon": "inspectIcon",
            "menuPid": 0,
            "englishName": null,
            "open": false,
            "selected": false,
            "children": [
              {
                "menuId": 23,
                "menuName": "过检人员管理",
                "menuType": "MENU",
                "menuSort": 1,
                "menuPath": "/erp/inspect/personverify/list",
                "menuIcon": "iconrenyuan",
                "menuPid": 5,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 24,
                "menuName": "过检车辆管理",
                "menuType": "MENU",
                "menuSort": 2,
                "menuPath": "/erp/inspect/carverify/list",
                "menuIcon": "iconcheliang",
                "menuPid": 5,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 26,
                "menuName": "车辆核查管理",
                "menuType": "MENU",
                "menuSort": 4,
                "menuPath": "/erp/inspect/car/list",
                "menuIcon": "iconjianchazhan-chelianghecha",
                "menuPid": 5,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 27,
                "menuName": "人员核查管理",
                "menuType": "MENU",
                "menuSort": 5,
                "menuPath": "/erp/inspect/person/list",
                "menuIcon": "iconrenyuan",
                "menuPid": 5,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 28,
                "menuName": "物品核查管理",
                "menuType": "MENU",
                "menuSort": 6,
                "menuPath": "/erp/inspect/goods/list",
                "menuIcon": "iconwupin",
                "menuPid": 5,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 29,
                "menuName": "战果管理",
                "menuType": "MENU",
                "menuSort": 7,
                "menuPath": "/erp/inspect/victory/list",
                "menuIcon": "iconwodezhanguo",
                "menuPid": 5,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 51,
                "menuName": "人车物关联",
                "menuType": "MENU",
                "menuSort": 9,
                "menuPath": "/erp/inspect/mancarperson/list",
                "menuIcon": "iconrenchewuguanlian",
                "menuPid": 5,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 52,
                "menuName": "处置流转",
                "menuType": "MENU",
                "menuSort": 10,
                "menuPath": "/erp/inspect/dispose/list",
                "menuIcon": "iconchuzhiliuzhuan",
                "menuPid": 5,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              }
            ]
          },
          {
            "menuId": 6,
            "menuName": "布控中心",
            "menuType": "MENU",
            "menuSort": 6,
            "menuPath": "/erp/deploy",
            "menuIcon": "bukongIcon",
            "menuPid": 0,
            "englishName": null,
            "open": false,
            "selected": false,
            "children": [
              {
                "menuId": 30,
                "menuName": "布控黑名单管理",
                "menuType": "MENU",
                "menuSort": 1,
                "menuPath": "/erp/deploy/black/list",
                "menuIcon": null,
                "menuPid": 6,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 31,
                "menuName": "布控白名单管理",
                "menuType": "MENU",
                "menuSort": 2,
                "menuPath": "/erp/deploy/white/list",
                "menuIcon": null,
                "menuPid": 6,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              }
            ]
          },
          {
            "menuId": 7,
            "menuName": "车证人证",
            "menuType": "MENU",
            "menuSort": 7,
            "menuPath": "/erp/znyp",
            "menuIcon": "queryIcon",
            "menuPid": 0,
            "englishName": null,
            "open": false,
            "selected": false,
            "children": [
              {
                "menuId": 36,
                "menuName": "车证合一",
                "menuType": "MENU",
                "menuSort": 4,
                "menuPath": "/erp/znyp/carlicense/list",
                "menuIcon": "iconqichezhengzhao",
                "menuPid": 7,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 37,
                "menuName": "人证合一",
                "menuType": "MENU",
                "menuSort": 5,
                "menuPath": "/erp/znyp/personlicense/list",
                "menuIcon": "iconrenzhengxiangfu",
                "menuPid": 7,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              }
            ]
          },
          {
            "menuId": 8,
            "menuName": "历史信息",
            "menuType": "MENU",
            "menuSort": 8,
            "menuPath": "/erp/history",
            "menuIcon": "historyIcon",
            "menuPid": 0,
            "englishName": null,
            "open": false,
            "selected": false,
            "children": [
              {
                "menuId": 38,
                "menuName": "车辆预警历史",
                "menuType": "MENU",
                "menuSort": 1,
                "menuPath": "/erp/history/carwarning/list",
                "menuIcon": "iconcheliangyujingxinxi",
                "menuPid": 8,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 39,
                "menuName": "人员预警历史",
                "menuType": "MENU",
                "menuSort": 2,
                "menuPath": "/erp/history/personwarning/list",
                "menuIcon": "iconrenyuanyujingxinxi",
                "menuPid": 8,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 49,
                "menuName": "车辆采集",
                "menuType": "MENU",
                "menuSort": 5,
                "menuPath": "/erp/history/carcollect/list",
                "menuIcon": "iconcheliangcaijijilu",
                "menuPid": 8,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 1000,
                "menuName": "人像采集",
                "menuType": "MENU",
                "menuSort": 100,
                "menuPath": "/erp/history/facecollect/list",
                "menuIcon": null,
                "menuPid": 8,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 50,
                "menuName": "通讯标签采集",
                "menuType": "MENU",
                "menuSort": 6,
                "menuPath": "/erp/history/tagcollect/list",
                "menuIcon": "iconxinhao",
                "menuPid": 8,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              }
            ]
          },
          {
            "menuId": 1001,
            "menuName": "预警中心",
            "menuType": "MENU",
            "menuSort": 101,
            "menuPath": "/erp/warning",
            "menuIcon": "warningIcon",
            "menuPid": 0,
            "englishName": null,
            "open": false,
            "selected": false
          },
          {
            "menuId": 3,
            "menuName": "用户管理",
            "menuType": "MENU",
            "menuSort": 9,
            "menuPath": "/erp/account",
            "menuIcon": "accountIcon",
            "menuPid": 0,
            "englishName": null,
            "open": false,
            "selected": false,
            "children": [
              {
                "menuId": 15,
                "menuName": "警员管理",
                "menuType": "MENU",
                "menuSort": 1,
                "menuPath": "/erp/account/police/list",
                "menuIcon": "iconjingyuanguanli",
                "menuPid": 3,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 16,
                "menuName": "角色管理",
                "menuType": "MENU",
                "menuSort": 2,
                "menuPath": "/erp/account/role/list",
                "menuIcon": "iconquanxianguanli",
                "menuPid": 3,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 17,
                "menuName": "权限管理",
                "menuType": "MENU",
                "menuSort": 3,
                "menuPath": "/erp/account/menu/list",
                "menuIcon": "iconjiaoseguanli",
                "menuPid": 3,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              }
            ]
          },
          {
            "menuId": 2,
            "menuName": "系统管理",
            "menuType": "MENU",
            "menuSort": 10,
            "menuPath": "/erp/system",
            "menuIcon": "systemIcon",
            "menuPid": 0,
            "englishName": null,
            "open": false,
            "selected": false,
            "children": [
              {
                "menuId": 11,
                "menuName": "日志管理",
                "menuType": "MENU",
                "menuSort": 3,
                "menuPath": "/erp/system/log/list",
                "menuIcon": "iconrizhiguanli",
                "menuPid": 2,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 12,
                "menuName": "字典管理",
                "menuType": "MENU",
                "menuSort": 4,
                "menuPath": "/erp/system/dictconfig/list",
                "menuIcon": "iconzidianguanli",
                "menuPid": 2,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 13,
                "menuName": "组织机构管理",
                "menuType": "MENU",
                "menuSort": 5,
                "menuPath": "/erp/system/organize/list",
                "menuIcon": "iconzuzhijigou",
                "menuPid": 2,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 14,
                "menuName": "任务管理",
                "menuType": "MENU",
                "menuSort": 6,
                "menuPath": "/erp/system/notice/list",
                "menuIcon": "iconrenwuguanli",
                "menuPid": 2,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              },
              {
                "menuId": 110,
                "menuName": "采集项显示管理",
                "menuType": "MENU",
                "menuSort": 7,
                "menuPath": "/erp/system/collectconfig/list",
                "menuIcon": "iconrenwuguanli",
                "menuPid": 2,
                "englishName": null,
                "open": false,
                "selected": false,
                "children": null
              }
            ]
          }
        ],
        "createDate": "2020-04-24T07:11:28.000+0000",
        "updateDate": "2020-04-24T07:11:28.000+0000"
      },
      "userPhone": "15208250461",
      "idCard": "511602199206018191",
      "extendField": "843329",
      "createDate": "2020-03-16T06:48:12.157+0000",
      "updateDate": "2020-05-01T09:45:28.225+0000",
      "checkCodes": [
        "5101060000010011"
      ],
      "screenMonitors": {
        "title": "南昌市公安检查站治安管控系统",
        "longitude": "115.84671020507812",
        "latitude": "28.703155517578125",
        "address": "10"
      },
      "cameraIndexCodes": [
        "01577685566777018586",
        "01577685764764018591",
        "01577689895721018855"
      ],
      "crossingIndexCodes": [
        "f8ab189d405d48a3bc586e8a9bd4fbd9"
      ]
    }
  }
}